/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as AdminLoginIndexRouteImport } from './routes/admin-login/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLoginBusinessRouteImport } from './routes/admin.login.business'
import { Route as AdminLoginIndividualRouteImport } from './routes/admin.login.individual'
import { Route as AdminLoginOverallRouteImport } from './routes/admin.login.overall'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/admin-login/',
  path: '/admin-login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginBusinessRoute = AdminLoginBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminLoginRoute,
} as any)
const AdminLoginIndividualRoute = AdminLoginIndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => AdminLoginRoute,
} as any)
const AdminLoginOverallRoute = AdminLoginOverallRouteImport.update({
  id: '/overall',
  path: '/overall',
  getParentRoute: () => AdminLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/login': typeof AdminLoginRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin-login/': typeof AdminLoginIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login/business': typeof AdminLoginBusinessRoute
  '/admin/login/individual': typeof AdminLoginIndividualRoute
  '/admin/login/overall': typeof AdminLoginOverallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/login': typeof AdminLoginRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin-login': typeof AdminLoginIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login/business': typeof AdminLoginBusinessRoute
  '/admin/login/individual': typeof AdminLoginIndividualRoute
  '/admin/login/overall': typeof AdminLoginOverallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/login': typeof AdminLoginRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin-login/': typeof AdminLoginIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login/business': typeof AdminLoginBusinessRoute
  '/admin/login/individual': typeof AdminLoginIndividualRoute
  '/admin/login/overall': typeof AdminLoginOverallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/directory'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/marketplace'
    | '/signup'
    | '/tracking'
    | '/admin/analytics'
    | '/admin/deals'
    | '/admin/login'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin-login/'
    | '/admin/'
    | '/admin/login/business'
    | '/admin/login/individual'
    | '/admin/login/overall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/directory'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/marketplace'
    | '/signup'
    | '/tracking'
    | '/admin/analytics'
    | '/admin/deals'
    | '/admin/login'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin-login'
    | '/admin'
    | '/admin/login/business'
    | '/admin/login/individual'
    | '/admin/login/overall'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/directory'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/marketplace'
    | '/signup'
    | '/tracking'
    | '/admin/analytics'
    | '/admin/deals'
    | '/admin/login'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin-login/'
    | '/admin/'
    | '/admin/login/business'
    | '/admin/login/individual'
    | '/admin/login/overall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DirectoryRoute: typeof DirectoryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SignupRoute: typeof SignupRoute
  TrackingRoute: typeof TrackingRoute
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login/': {
      id: '/admin-login/'
      path: '/admin-login'
      fullPath: '/admin-login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/business': {
      id: '/admin/login/business'
      path: '/business'
      fullPath: '/admin/login/business'
      preLoaderRoute: typeof AdminLoginBusinessRouteImport
      parentRoute: typeof AdminLoginRoute
    }
    '/admin/login/individual': {
      id: '/admin/login/individual'
      path: '/individual'
      fullPath: '/admin/login/individual'
      preLoaderRoute: typeof AdminLoginIndividualRouteImport
      parentRoute: typeof AdminLoginRoute
    }
    '/admin/login/overall': {
      id: '/admin/login/overall'
      path: '/overall'
      fullPath: '/admin/login/overall'
      preLoaderRoute: typeof AdminLoginOverallRouteImport
      parentRoute: typeof AdminLoginRoute
    }
  }
}

interface AdminLoginRouteChildren {
  AdminLoginBusinessRoute: typeof AdminLoginBusinessRoute
  AdminLoginIndividualRoute: typeof AdminLoginIndividualRoute
  AdminLoginOverallRoute: typeof AdminLoginOverallRoute
}

const AdminLoginRouteChildren: AdminLoginRouteChildren = {
  AdminLoginBusinessRoute: AdminLoginBusinessRoute,
  AdminLoginIndividualRoute: AdminLoginIndividualRoute,
  AdminLoginOverallRoute: AdminLoginOverallRoute,
}

const AdminLoginRouteWithChildren = AdminLoginRoute._addFileChildren(
  AdminLoginRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminLoginRoute: typeof AdminLoginRouteWithChildren
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminLoginRoute: AdminLoginRouteWithChildren,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DirectoryRoute: DirectoryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  SignupRoute: SignupRoute,
  TrackingRoute: TrackingRoute,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
